// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBCwt3GmpxVcGWH58CULtWRh-4snbJ1IY',
    appId: '1:839468636765:web:6f029569314405bfb70bb4',
    messagingSenderId: '839468636765',
    projectId: 'restaurant-os-68c79',
    storageBucket: 'restaurant-os-68c79.firebasestorage.app',
    authDomain: 'restaurant-os-68c79.firebaseapp.com',
    databaseURL: 'https://restaurant-os-68c79-default-rtdb.firebaseio.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHM1cHT5WFrpl4_zSEgJa5my4NwZvigOc',
    appId: '1:839468636765:android:25488fb6bf5a5cf5b70bb4',
    messagingSenderId: '839468636765',
    projectId: 'restaurant-os-68c79',
    storageBucket: 'restaurant-os-68c79.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCuJpcNMWFvINTW7Mr2VNhfTNDF1R_6QZ4',
    appId: '1:839468636765:ios:a7f48d550eb74859b70bb4',
    messagingSenderId: '839468636765',
    projectId: 'restaurant-os-68c79',
    storageBucket: 'restaurant-os-68c79.firebasestorage.app',
    iosBundleId: 'com.aiudalabs.restaurantos.kitchen',
  );

}