[options]
addons_path = /mnt/extra-addons,/usr/lib/python3/dist-packages/odoo/addons
data_dir = /var/lib/odoo
db_host = db
db_port = 5432
db_user = odoo
db_password = odoo_demo_2024
http_port = 8069
log_level = warn
admin_passwd = $pbkdf2-sha512$600000$hpAyxjgnxLj33hsj5BxDyA$IiNy73pizjnv7apg8rEnwNwfrH7KsMhOeVa9uPA.twv60O2T/4LW/V7lTwo6kmngx032EmDnv5etz817V1AgCQ

